# Generated by Django 5.2.7 on 2025-11-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_custom_phone_alter_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custom',
            name='otp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
